legacy_layout=false
horizontal
position=top-left
background_alpha=0.45
round_corners=8
font_size=22
gpu_stats
gpu_temp
gpu_power
cpu_stats
cpu_temp
ram
vram
fps
frametime
frame_timing
gamemode
vulkan_driver
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
output_folder=/home/tommy/Documents/MangoHud
